services:
  order-postgres:
    image: postgres:17
    container_name: order-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: order-db
    ports:
      - "5434:5432"
    networks:
      - localstack_network
    restart: unless-stopped

  payment-postgres:
    image: postgres:17
    container_name: payment-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: payment-db
    ports:
      - "5432:5432"
    networks:
      - localstack_network
    restart: unless-stopped

  order:
    build:
      context: .
      dockerfile: docker/order/Dockerfile
    container_name: spring-boot-java-eda-order
    image: spring-boot-java-eda-order:latest
    environment:
      SPRING_CLOUD_AWS_SNS_ENDPOINT: http://localstack:4566
      SPRING_CLOUD_AWS_SQS_ENDPOINT: http://localstack:4566
      SPRING_DATASOURCE_URL: jdbc:postgresql://order-postgres:5432/order-db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    depends_on:
      - order-postgres
      - localstack
    networks:
      - localstack_network
    ports:
      - "8080:8080"
    restart: unless-stopped

  payment:
    build:
      context: .
      dockerfile: docker/payment/Dockerfile
    container_name: spring-boot-java-eda-payment
    image: spring-boot-java-eda-payment:latest
    environment:
      SPRING_CLOUD_AWS_SNS_ENDPOINT: http://localstack:4566
      SPRING_CLOUD_AWS_SQS_ENDPOINT: http://localstack:4566
      SPRING_DATASOURCE_URL: jdbc:postgresql://payment-postgres:5432/payment-db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    depends_on:
      - payment-postgres
      - localstack
    networks:
      - localstack_network
    ports:
      - "8081:8081"
    restart: unless-stopped

  localstack:
    image: localstack/localstack:4.8.0
    container_name: localstack
    ports:
      - "127.0.0.1:4566:4566"
      - "127.0.0.1:4510-4559:4510-4559"
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
      - LOCALSTACK_SERVICES=sqs,sns
      - PERSISTENCE=/var/lib/localstack/data
    volumes:
      - "./docker/localstack/init-localstack.sh:/etc/localstack/init/ready.d/init-localstack.sh"
      - "/var/run/docker.sock:/var/run/docker.sock"
    command: chmod +x /etc/localstack/init/ready.d/init-localstack.sh
    networks:
      - localstack_network

networks:
  localstack_network:
    driver: bridge
