server:
  port: 8081
spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1}
    username: ${SPRING_DATASOURCE_USERNAME:sa}
    password: ${SPRING_DATASOURCE_PASSWORD:}
  cloud:
    aws:
      credentials:
        access-key: test
        secret-key: test
      region:
        static: us-east-1
      sns:
        endpoint: ${SPRING_CLOUD_AWS_SNS_ENDPOINT:http://localhost:4566}
      sqs:
        endpoint: ${SPRING_CLOUD_AWS_SQS_ENDPOINT:http://localhost:4566}
  application:
    name: sample
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /
app:
  queues:
    order-created: order-created-queue
  topics:
    payment-completed: payment-completed-topic
    payment-failed: payment-failed-topic
