server:
  port: 8081
spring:
  cloud:
    aws:
      credentials:
        access-key: test
        secret-key: test
      region:
        static: us-east-1
      sns:
        endpoint: http://localhost:4566
      sqs:
        endpoint: http://localhost:4566
  application:
    name: sample
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /
